#include <linux/init.h> 
#include <linux/module.h> 
#include <linux/kernel.h> 
#include <linux/platform_device.h>      /* For platform devices */ 
#include <linux/gpio/consumer.h>        /* For GPIO Descriptor */ 
#include <linux/interrupt.h>            /* For IRQ */ 
#include <linux/of.h>   

/**
 * Interrupt generated by a button
 * IRQ Handler will be called once gpio5 is set to low
 * pinout https://www.elektronik-kompendium.de/sites/raspberry-pi/1907101.htm
 * Following is added to the device tree arch/arm/boot/dts/bcm2710-rpi-3-b-plus.dts
	btn_device {
		compatible="btn_device_driver";
		btn-gpio= <&gpio 5 GPIO_ACTIVE_LOW>;
		status = "okay";
	};
 * Reference https://learning.oreilly.com/library/view/linux-device-drivers/9781785280009/fc82e0c9-741d-4141-b99e-272bbe997468.xhtml	
*/

static struct gpio_desc* btn;
static int irq;

struct of_device_id btn_ids[]= 
{
    {.compatible = "btn_device_driver", },
    {}
};


static irqreturn_t btn_irq_handler(int irq, void *dev_id) 
{ 
    pr_info("btn interrupt ! \n"); 
    return IRQ_HANDLED; 
}

static int btn_drv_probe (struct platform_device *pdev) 
{ 
    int retval; 
    struct device *dev = &pdev->dev; 
 
    btn = gpiod_get(dev, "btn", GPIOD_IN); 
    retval = PTR_ERR(btn);
	if (IS_ERR(btn))
    {
        pr_err("Problem finding the btn-gpio in the device tree \n");
        goto out;
    }

    irq = gpiod_to_irq(btn); 
    if (irq <0)
    {
        dev_err(dev, "GPIO %d has no interrupt\n", desc_to_gpio(btn));
		return -EINVAL;
    }

    retval = request_threaded_irq(irq, NULL,\ 
                            btn_irq_handler, \ 
                            IRQF_TRIGGER_LOW | IRQF_ONESHOT, \
                            "button interrupt", NULL); 
    
    pr_info("Hello! btn device probed! irq = %d\n", irq); 

out:
    return retval; 
} 
 
static int btn_drv_remove(struct platform_device *pdev) 
{ 
    free_irq(irq, NULL);  
    gpiod_put(btn); 
    pr_info("good bye btn !\n"); 
    return 0;
}

static struct platform_driver btn_drv =
{
    .probe= btn_drv_probe,
    .remove= btn_drv_remove,
    .driver = {
        .name = "button driver",
        .of_match_table=of_match_ptr(btn_ids),
        .owner= THIS_MODULE,
    },
};

module_platform_driver(btn_drv);

MODULE_DESCRIPTION("bouton interrupts");
MODULE_AUTHOR("Achraf Boussetta <boussettaachraf26@gmail.com>");
MODULE_LICENSE("GPL");


